### PR TITLE
More fixes again

### LINKED ISSUE #420: Add TS1 mechanism configuraiton and initial condtions
Add [TS1.zip](https://github.com/user-attachments/files/16433723/TS1.zip) as an example that can be retrieved by the API

**Acceptance criteria**
- in `interactive/api/static/examples` a new folder for TS1 is created with the proper mechanism and conditions
- `api/load-example?example=TS1` returns the TS1 configuration

### PR DESCRIPTION
**Pull request by K20shores**
This removes concentrations, environmental conditions form the configuration files. The concentrations are placed into my_config.js. I also made sure any error from music box gets sent back to the UI. This creates something that runs TS1, but we have much to do to fix the initial conditions

I think this closes #420

### CODE REVIEW

**Comment by carl-drews** [comment]
I will pull down this branch and run it with my command-line music_box.py.

**Comment by carl-drews** [comment]
Carl Drews   9:05 AM
Your new TS1 runs to completion with my "transpose-TS1-python" main. mySolution.csv has output that looks like chemistry.

**Review by carl-drews — APPROVED** [review]
**Suggestion**: Can we run maybe 2-3 hours? I think the scientists might like to see some more output, and this example finishes quickly.

**Comment by K20shores** [comment]
@carl-drews that's easily changed in the UI. We can show them how in the demo tomorrow as a short little exercise

**Pull request merged**
